### ISSUE TITLE
No messages in the chat window when running on local (Node LTS, Linux and Windows 11)

### ISSUE THREAD

**Issue by basraven** [diwash007/kurakani#12]
I love the project and tried to run on on my local machine
(Node LTS, tried on both Linux and Windows)
On both machines I'm getting the same errors:

1. First the following needs to be patched to get the frontend running in the first place:
`npm install ws bufferutil utf-8-validate` without that I'm getting build errors when running `npm run dev`.
2. Once I run both the frontend and backend in different terminals on the same machine I'm not getting any errors and the server tells me "SERVER RUNNING". 
3. Once  I try to add messages in the chat window (once I enter a room),
the messages that I'm sending are not even showing in my own chat window (let alone other's chat window.)

Would highly appreciate if you could check if there's a fix for that.

**Comment by diwash007** [comment]
I ll look into it

**Comment by diwash007** [comment]
Hello @basraven,
Thank you for checking out this project.
I read your issue and tried to run the project locally from scratch.
It worked without any issues.
Could you let me know if you set up the required Environment variables for the project?

**Comment by diwash007** [comment]
I recently encountered the issue you encountered. 
I have pushed the fix for it.
Thanks for reporting.

**Comment by basraven** [comment]
Hi @diwash007,
Thanks for the fix, this did it for me, it works now
You're awesome! :)
Happy weekend!
Seb

**Comment by diwash007** [comment]
You're welcome, Seb.
Have a great weekend! 😊
