### ISSUE TITLE
'Star on Github' button aligns on left side for mobile screens.

### ISSUE THREAD

**Issue by ashikjhonson** [diwash007/kurakani#14]
The button must be aligned with menu icon & must be aligned on right side.

SS
<img width="193" alt="Screenshot 2023-10-07 221443" src="https://github.com/diwash007/kurakani/assets/97791612/0652e45d-445a-485e-87b6-158a14bc5791">

I would like to work on this issue.

**Comment by diwash007** [comment]
Can you please elaborate more?
Like how would it look afterwards?

**Comment by ashikjhonson** [comment]
I think it would be better to be positioning it on top right corner & for now it doesn't seems to be a button or link, need to give some background or border for it.

**Comment by diwash007** [comment]
Alrighty, you may work on it.
