### ISSUE TITLE
Persist user on page refresh

### ISSUE THREAD

**Issue by diwash007** [diwash007/kurakani#2]
Currently users are redirected to homepage on page refresh i.e. socket disconnection

**Comment by Maryam-bit** [comment]
Hello @diwash007 ,

I hope you're doing well. I am interested in addressing this issue , as I am participating in Hacktoberfest. Could you please assign this issue to me?

Thank you for your assistance.

Best regards,
Maryam Noor

**Comment by diwash007** [comment]
> Hello @diwash007 ,
> 
> I hope you're doing well. I am interested in addressing this issue , as I am participating in Hacktoberfest. Could you please assign this issue to me?
> 
> Thank you for your assistance.
> 
> Best regards, Maryam Noor

sure

**Comment by diwash007** [comment]
Thank you @Maryam-bit
