### ISSUE TITLE
[feat]: Implement Background Click Close Functionality

### ISSUE THREAD

**Issue by purnasth** [diwash007/kurakani#23]
# Issue Title: Implement Background Click Close Functionality for **Create or Join Room Popup**

## Issue Description
This improvement suggests enabling the functionality that allows users to close the modal by clicking outside of the form, specifically in the background area.

## Proposed Changes
- Implement functionality enabling the modal to close when users click outside of the form's boundary on the background area.
- Ensure the modal automatically dismisses when users interact with the background, providing a more intuitive and user-friendly experience.

## Attachments
![image](https://github.com/diwash007/kurakani/assets/107195487/26a37db4-389a-4858-97bd-b8672a818cd3)

## Additional Information
Adding the functionality to close the modal by clicking on the background area will enhance the user experience by providing an additional way to dismiss the form. 

Please assign this issue to me so that I can start working on implementing this feature.

**Comment by diwash007** [comment]
done
