### ISSUE TITLE
Create a full fledged chat app 

### ISSUE THREAD

**Issue by thenishantsapkota** [diwash007/kurakani#25]
This will help us create a full fledged chat application along with user authentication, authorization, persisting of messages using a database and will make the platform functional and minimalistic to use.

**Comment by diwash007** [comment]
The sole reason behind developing this web app is to have instant messaging platform without any hassle to register and logging in.

**Comment by diwash007** [comment]
Is this you writing the issue description or a bot/AI?

**Comment by thenishantsapkota** [comment]
It is me writing the comment. Haven't used any AI tools.
